#!/usr/bin/env python2

from gqu import Portage
from argparse import ArgumentParser
import logging

parser = ArgumentParser(description = 'Quick Gentoo upgrade calculator')
parser.add_argument('--sync', '-s', action = 'store_true', default = False, help = 'synchronize version data')

logging.basicConfig(level=logging.DEBUG)
log = logging.getLogger('upgrade')

args = parser.parse_args()
portage = Portage(args)
portage.upgrade()
